In [24]:
import pandas as pd
url = 'https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_data/main/bfro_reports_fall2022.csv'
df = pd.read_csv(url)
df.head()

,observed,location_details,county,state,season,title,latitude,longitude,date,number,...,precip_intensity,precip_probability,precip_type,pressure,summary,uv_index,visibility,wind_bearing,wind_speed,location
0,Ed L. was salmon fishing with a companion in P...,East side of Prince William Sound,Valdez-Chitina-Whittier County,Alaska,Fall,NaN,NaN,NaN,NaN,1261.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,heh i kinda feel a little dumb that im reporti...,"the road is off us rt 80, i dont know the exit...",Warren County,New Jersey,Fall,NaN,NaN,NaN,NaN,438.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I was on my way to Claremont from Lebanon on R...,Close to Claremont down 120 not far from Kings...,Sullivan County,New Hampshire,Summer,Report 55269: Dawn sighting at Stevens Brook o...,43.41549,-72.33093,2016-06-07,55269.0,...,0.001,0.7,rain,998.87,Mostly cloudy throughout the day.,6.0,9.70,262.0,0.49,POINT(-72.33093000000001 43.415490000000005)
3,I was northeast of Macy Nebraska along the Mis...,Latitude & Longitude : 42.158230 -96.344197,Thurston County,Nebraska,Spring,Report 59757: Possible daylight sighting of a ...,42.15685,-96.34203,2018-05-25,59757.0,...,0.000,0.0,NaN,1008.07,Partly cloudy in the morning.,10.0,8.25,193.0,3.33,POINT(-96.34203000000001 42.15685)
4,"While this incident occurred a long time ago, ...","Ward County, Just outside of a the Minuteman T...",Ward County,North Dakota,Spring,Report 751: Hunter describes described being s...,48.25422,-101.31660,2000-04-21,751.0,...,NaN,NaN,rain,1011.47,Partly cloudy until evening.,6.0,10.00,237.0,11.14,POINT(-101.3166 48.254220000000004)

In [25]:
state_counts = df['state'].value_counts().reset_index()
state_counts.columns = ['state', 'count']
state_counts.head()

        state  count
0  Washington    563
1  California    402
2     Florida    292
3        Ohio    276
4      Oregon    241

In [26]:
import altair as alt
bar_chart = alt.Chart(state_counts).mark_bar().encode(
    x=alt.X('count:Q', title='Number of Sightings'), y=alt.Y('state:N', sort='-x', title='State'),
    color=alt.Color('count:Q', scale=alt.Scale(scheme='reds'))
).properties(
    title='Bigfoot Sightings by State',
    width=600, height=600
)
bar_chart

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4747 entries, 0 to 4746
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   observed            4711 non-null   object
 1   location_details    4008 non-null   object
 2   county              4747 non-null   object
 3   state               4747 non-null   object
 4   season              4747 non-null   object
 5   title               3797 non-null   object
 6   latitude            3797 non-null   float64
 7   longitude           3797 non-null   float64
 8   date                3797 non-null   object
 9   number              4747 non-null   float64
 10  classification      4747 non-null   object
 11  geohash             3797 non-null   object
 12  temperature_high    3098 non-null   float64
 13  temperature_mid     2950 non-null   float64
 14  temperature_low     2953 non-null   float64
 15  dew_point           3133 non-null   float64
 16  humidity            3133 non-null   float64
 17  cloud_cover         2853 non-null   float64
 18  moon_phase          3156 non-null   float64
 19  precip_intensity    2493 non-null   float64
 20  precip_probability  2493 non-null   float64
 21  precip_type         1560 non-null   object
 22  pressure            2411 non-null   float64
 23  summary             3156 non-null   object
 24  uv_index            3156 non-null   float64
 25  visibility          2817 non-null   float64
 26  wind_bearing        3147 non-null   float64
 27  wind_speed          3149 non-null   float64
 28  location            3797 non-null   object
dtypes: float64(17), object(12)
memory usage: 1.1+ MB

In [28]:
df.columns

Index(['observed', 'location_details', 'county', 'state', 'season', 'title',
       'latitude', 'longitude', 'date', 'number', 'classification', 'geohash',
       'temperature_high', 'temperature_mid', 'temperature_low', 'dew_point',
       'humidity', 'cloud_cover', 'moon_phase', 'precip_intensity',
       'precip_probability', 'precip_type', 'pressure', 'summary', 'uv_index',
       'visibility', 'wind_bearing', 'wind_speed', 'location'],
      dtype='object')

In [31]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['year'] = df['date'].dt.year

yearly_counts = df['year'].value_counts().sort_index().reset_index()
yearly_counts.columns = ['year', 'count']

In [34]:
bar_plot = alt.Chart(yearly_counts).mark_bar().encode(
    x='year:O', y='count:Q',
    color=alt.Color('count:Q', scale=alt.Scale(scheme='Blues'))
).properties(
    title='Bigfoot Sighting by Year',
    width=600, height=600
)
bar_plot

alt.Chart(...)

In [33]:
bar_plot = alt.Chart(yearly_counts).mark_bar().encode(
    x='year:O', y='count:Q',
    color=alt.Color('count:Q', scale=alt.Scale(scheme='blues')),
    tooltip=['year', 'count']
).properties(
    title='Bigfoot Sighting by Year',
    width=600, height=600
)
bar_plot

alt.Chart(...)